### ISSUE TITLE
Android - возможность использования без GMS (Google Services)

### ISSUE THREAD

**Issue by Sash0k** [deemru/Chromium-Gost#98]
При запуске на устройствах без GMS приложение падает при переходе с первого экрана при нажатии кнопки "Продолжить"

```
                 Process: org.chromium.chrome.stable, PID: 22334
                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.BaseBundle.putBoolean(java.lang.String, boolean)' on a null object reference
                 	at X80.f(chromium-ChromePublic.apk-stable-636707804:157)
                 	at org.chromium.chrome.browser.firstrun.FirstRunActivity.Y1(chromium-ChromePublic.apk-stable-636707804:5)
                 	at org.chromium.chrome.browser.signin.SigninFirstRunFragment.w1(chromium-ChromePublic.apk-stable-636707804:9)
                 	at mc0.run(chromium-ChromePublic.apk-stable-636707804:53)
                 	at rc0.onClick(chromium-ChromePublic.apk-stable-636707804:14)
                 	at android.view.View.performClick(View.java:7455)
                 	at android.view.View.performClickInternal(View.java:7432)
                 	at android.view.View.access$3700(View.java:835)
                 	at android.view.View$PerformClick.run(View.java:28810)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7870)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Воспроизвёл на двух устройствах с прошивками без сервисов Google (только HMS и чистый AOSP). 
Версия **124.0.6367.78**

Планируется ли исправить это, и возможно ли вообще отвязать хромиум от гугл-сервисов? Также выдержка из лога, где приложение пишет об их отсутствии:

```
23:52:13.436  W  org.chromium.chrome.stable requires the Google Play Store, but it is missing.
23:52:13.437  E  Error fetching accounts from the delegate.
                 org.chromium.components.signin.AccountManagerDelegateException: Can't use Google Play Services
                 	at dF1.a(chromium-ChromePublic.apk-stable-636707804:61)
                 	at q1.b(chromium-ChromePublic.apk-stable-636707804:5)
                 	at Ld.call(chromium-ChromePublic.apk-stable-636707804:9)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 	at Od.run(chromium-ChromePublic.apk-stable-636707804:26)
                 	at qq1.run(chromium-ChromePublic.apk-stable-636707804:8)
                 	at eR1.f(chromium-ChromePublic.apk-stable-636707804:68)
                 	at cR1.run(chromium-ChromePublic.apk-stable-636707804:3)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:920) 

```

**Comment by deemru** [comment]
@crypto-das как будет время, можешь пожалуйста посмотреть на 'org.chromium.chrome.browser.signin', есть ли там возможность отключить все сценарии (firstrun и т.д.) и привязки к сервисам Гугл?

С виду, какие-то разовые вещи не отрабатывают, вероятно никак дальше на работу не влияющие.

**Comment by Sash0k** [comment]
я сам посмотрел, и нашёл эти патчи для отвязки хромиума от GMS:
https://github.com/ungoogled-software/ungoogled-chromium-android/commit/25826b626ec6d2afb5bedff46122ed8fafb34bda
https://github.com/ungoogled-software/ungoogled-chromium-android/commit/cb331f5cdb0ee426b08235e309c26ed40c92c567

**Comment by deemru** [comment]
> я сам посмотрел, и нашёл эти патчи для отвязки хромиума от GMS: [ungoogled-software/ungoogled-chromium-android@25826b6](https://github.com/ungoogled-software/ungoogled-chromium-android/commit/25826b626ec6d2afb5bedff46122ed8fafb34bda) [ungoogled-software/ungoogled-chromium-android@cb331f5](https://github.com/ungoogled-software/ungoogled-chromium-android/commit/cb331f5cdb0ee426b08235e309c26ed40c92c567)

Спасибо, надеюсь @crypto-das посмотрит
